
import React, { createContext, useState, useContext, ReactNode } from 'react';

export type Language = 'ko' | 'en' | 'ja' | 'th';

type Translations = {
  [key in Language]: {
    [key: string]: string;
  };
};

const translations: Translations = {
  ko: {
    // Auth
    app_desc: "골프 레슨 분석 & 관리 플랫폼",
    coach_login: "코치님 로그인",
    client_login: "회원님 로그인",
    admin_login: "관리자 로그인",
    email: "이메일",
    password: "비밀번호",
    name: "이름",
    phone: "전화번호",
    phone_desc: "*레슨 기록 연동을 위해 정확한 번호를 입력해주세요.",
    auto_login: "자동 로그인",
    login_btn: "로그인",
    signup_btn: "회원가입",
    signup_msg: "계정이 없으신가요? 회원가입하기",
    login_msg: "이미 계정이 있으신가요? 로그인하기",
    admin_only: "시스템 관리자 전용 페이지입니다.",
    find_account: "아이디/비밀번호 찾기",
    find_email_title: "이메일(ID) 찾기",
    find_pw_title: "비밀번호 찾기",
    find_btn: "찾기",
    result_email: "회원님의 이메일은 다음과 같습니다:",
    result_pw: "회원님의 비밀번호는 다음과 같습니다:",
    not_found: "일치하는 정보를 찾을 수 없습니다.",
    // Common
    logout: "로그아웃",
    cancel: "취소",
    save: "저장",
    confirm: "확인",
    delete: "삭제",
    edit: "수정",
    back: "돌아가기",
    loading: "로딩 중...",
    // Coach Dashboard
    coach_dashboard: "레슨 관리 대시보드",
    coach_dashboard_desc: "회원님의 레슨을 기록하고 관리하세요.",
    start_lesson: "레슨 시작",
    reservation_management: "예약 관리",
    no_lessons: "기록된 레슨이 없습니다",
    no_lessons_desc: "상단의 '레슨 시작' 버튼을 눌러 첫 레슨을 기록해보세요.",
    // Client Dashboard
    today_mission: "오늘의 미션",
    no_mission_today: "오늘 예정된 과제가 없습니다.",
    mission_manage: "미션 관리",
    ai_recommend: "AI 추천",
    stats: "데이터 통계",
    my_info: "내 정보 설정",
    recent_records: "최근 기록",
    no_records: "아직 기록이 없습니다",
    no_records_desc: "첫 연습이나 레슨을 기록해보세요!",
    // Roles
    coach: "프로",
    client: "회원",
    // CoachX
    coachx_subtitle: "AI 골프 코칭 인텔리전스",
    coachx_entry_label: "CoachX 열기",
    coachx_entry_desc: "AI 인사이트 & 코칭 허브",
    coachx_tab_insights: "인사이트",
    coachx_tab_members: "회원 성장",
    coachx_tab_curriculum: "커리큘럼",
    coachx_stat_lessons: "레슨 기록",
    coachx_stat_members: "담당 회원",
    coachx_stat_improving: "성장 중",
    coachx_stat_attention: "집중 케어",
    coachx_ask_title: "CoachX에게 질문하기",
    coachx_ask_desc: "레슨 데이터 기반 AI 코칭 어시스턴트",
    coachx_insights_section: "오늘의 CoachX 인사이트",
    coachx_attention_label: "집중 케어가 필요한 회원",
    coachx_stagnation_watch: "성장 주의 필요 회원",
    coachx_no_members: "레슨 기록이 없습니다. 첫 레슨을 기록해보세요!",
    coachx_curriculum_section: "추천 커리큘럼 & 코치 성장",
    coachx_per_member_curriculum: "회원별 추천 커리큘럼",
    coachx_suggested_prompts: "추천 질문",
    coachx_chat_placeholder: "CoachX에게 질문하세요...",
    // MemberReportCard
    coachx_trend_improving: "성장 중",
    coachx_trend_plateau: "정체 구간",
    coachx_trend_new: "초기 단계",
    coachx_trend_inactive: "장기 미레슨",
    coachx_lesson_count: "레슨 {n}회",
    coachx_days_ago: "{n}일 전",
    coachx_attention_high: "집중 케어 필요",
    coachx_attention_medium: "진행 중",
    coachx_attention_low: "안정적",
    coachx_section_report: "성장 리포트",
    coachx_section_curriculum: "커리큘럼",
    coachx_section_drills: "추천 드릴",
    coachx_repeated_issues: "반복 교정 포인트",
    coachx_strengths: "강화된 영역",
    coachx_suggested_focus: "다음 레슨 집중 방향",
    coachx_plateau_tip: "같은 문제가 반복되고 있습니다. 새로운 드릴 접근법이나 다른 주제로의 전환을 고려해보세요.",
    coachx_inactive_tip: "오랫동안 레슨이 없었습니다. 재참여 메시지나 목표 재설정 레슨을 권장합니다.",
    coachx_curriculum_5_sessions: "추천 5회 커리큘럼",
    coachx_drill_suggestions: "추천 연습 드릴",
    coachx_suggested_drills_short: "추천 드릴",
    coachx_drills_note: "드릴은 회원의 현재 수준에 맞게 조정하여 사용하세요.",
    // Coach Growth tab
    coachx_tab_coach_growth: "코치 성장",
    coachx_growth_activity_title: "레슨 활동 현황",
    coachx_growth_this_month: "이번 달",
    coachx_growth_last_month: "지난 달",
    coachx_growth_active_members: "활동 회원",
    coachx_growth_avg_sessions: "회원 평균",
    coachx_growth_topic_breakdown: "레슨 주제 분석",
    coachx_growth_teaching_strengths: "코치 강점 영역",
    coachx_growth_opportunities: "성장 기회 영역",
    coachx_growth_recommended_actions: "추천 코치 성장 액션",
    coachx_growth_member_snapshot: "회원 성장 현황",
    coachx_growth_no_data: "레슨을 기록하면 코치 성장 분석이 제공됩니다.",
    coachx_growth_lessons_unit: "레슨",
    coachx_growth_sessions_unit: "회",
    coachx_growth_trend_improving: "성장 중",
    coachx_growth_trend_plateau: "정체 구간",
    coachx_growth_trend_new: "초기 단계",
    coachx_growth_trend_inactive: "미레슨",
    coachx_growth_opportunities_all_covered: "다양한 영역을 가르치고 있습니다! 🎉",
    coachx_growth_topic_count: "{n}회 ({pct}%)",
    coachx_growth_vs_prev: "전월 대비",
    coachx_growth_ai_summary_title: "AI 코치 성장 분석",
    coachx_growth_ai_summary_loading: "AI가 코치 성장 분석을 생성 중입니다…",
    // CoachX Live tab (inside CoachX Hub)
    coachx_tab_live: "라이브",
    coachx_live_section_title: "CoachX 라이브 현황",
    coachx_live_today_sessions: "오늘의 레슨 기록",
    coachx_live_today_sessions_count: "{n}건 기록됨",
    coachx_live_no_sessions_today: "오늘 기록된 레슨이 없습니다.",
    coachx_live_member_status: "회원 현황",
    coachx_live_action_items: "즉시 실행 항목",
    coachx_live_no_actions: "모든 회원이 순조롭게 성장 중입니다! 🎉",
    coachx_live_inactive_action: "{name} — 재활성화 레슨을 권장합니다.",
    coachx_live_plateau_action: "{name} — 성장 돌파 집중 레슨을 권장합니다.",
    coachx_live_recent_activity: "최근 활동",
    coachx_live_ask_coachx: "CoachX에게 물어보기",
    coachx_live_no_data: "레슨을 기록하면 라이브 현황이 표시됩니다.",
    // CoachX Preview Strip (home)
    coachx_preview_title: "CoachX 라이브 현황",
    coachx_preview_view_all: "전체 보기",
    coachx_preview_open_label: "CoachX 허브 열기",
    coachx_preview_improving: "성장 중",
    coachx_preview_plateau: "정체 구간",
    coachx_preview_inactive: "장기 미레슨",
    coachx_preview_new: "신규",
    coachx_preview_urgency_suffix: "회원 — 집중 케어 또는 재참여 레슨을 권장합니다.",
    // CoachX Member History tab
    coachx_section_history: "레슨 이력",
    coachx_history_monthly_activity: "월별 레슨 현황",
    coachx_history_recent_lessons: "최근 레슨 기록",
    coachx_history_empty: "이전 레슨 기록이 없습니다.",
    coachx_history_untitled: "레슨",
    coachx_ask_about_member: "{name} 회원 CoachX 분석",
    // CoachX urgency badge (home entry button)
    coachx_urgency_n_members: "{n}명 집중 케어 필요",
    coachx_urgency_one_member: "1명 집중 케어 필요",
    // CoachX integration in client list
    coachx_client_ask_coachx: "CoachX 분석",
    // PR #108 – member growth detail screen
    coachx_view_full_report: "전체 리포트",
    coachx_growth_score_label: "성장 점수",
    coachx_growth_score_breakdown: "성장 점수",
    coachx_growth_score_desc: "레슨 빈도, 이슈 해결률, 성장 추세, 레슨 주기를 종합한 점수입니다.",
    coachx_issue_resolution_rate: "이슈 해결률",
    coachx_issue_resolution_desc: "초기 레슨 반복 이슈 대비 최근 레슨에서 해소된 비율입니다.",
    coachx_lesson_cadence_title: "레슨 주기",
    coachx_cadence_avg_days: "평균 주기(일)",
    coachx_cadence_value: "레슨 평균 간격: {n}일",
    coachx_cadence_excellent: "매우 규칙적",
    coachx_cadence_good: "규칙적",
    coachx_cadence_moderate: "보통",
    coachx_cadence_low: "불규칙",
    coachx_cadence_insufficient_data: "데이터 부족",
    coachx_weekly_activity_title: "최근 8주 레슨 활동",
    coachx_growth_metrics_title: "성장 지표",
    coachx_topic_progression_title: "레슨 주제 변화",
    coachx_topic_early: "초기 레슨",
    coachx_topic_recent: "최근 레슨",
    coachx_topic_no_data: "데이터 없음",
    coachx_topic_resolved: "해결됨",
    coachx_topic_ongoing: "진행 중",
    coachx_topic_new_focus: "새 주제",
    coachx_topic_progression_empty: "아직 주제 변화를 분석할 충분한 레슨 데이터가 없습니다.",
    coachx_detail_summary_title: "코칭 요약",
    coachx_detail_summary_improving: "꾸준히 성장하고 있습니다. 최근 레슨에서 다양한 영역을 다루며 진전을 보이고 있습니다. 현재 흐름을 유지하고 다음 단계로 이어가세요.",
    coachx_detail_summary_plateau: "최근 같은 주제가 반복되고 있습니다. 새로운 접근 방식이나 드릴을 도입하면 정체 구간을 벗어나는 데 도움이 됩니다.",
    coachx_detail_summary_inactive: "오랫동안 레슨이 없었습니다. 재참여 메시지나 짧은 목표 재설정 레슨으로 다시 연결해보세요.",
    coachx_detail_summary_new: "이제 막 시작한 단계입니다. 기초를 탄탄하게 쌓는 것이 중요합니다. 지속적인 레슨이 빠른 성장을 만듭니다.",
    coachx_detail_actions_title: "추천 코칭 액션",
    coachx_detail_action_reengage: "재참여 메시지를 보내거나 목표 재설정 레슨을 예약하세요.",
    coachx_detail_action_fresh_approach: "새로운 드릴 방법이나 다른 주제로 전환해 정체 구간을 돌파하세요.",
    coachx_detail_action_increase_cadence: "레슨 주기를 단축하면 성장 속도가 빨라집니다. 주 1회 이상 레슨을 권장합니다.",
    coachx_detail_action_resolve_issues: "반복되는 이슈에 집중하여 해결에 도달할 수 있도록 드릴을 강화하세요.",
    coachx_detail_action_next_focus: "{topic} 을(를) 다음 레슨의 집중 주제로 삼아보세요.",
    coachx_detail_action_keep_momentum: "좋은 흐름입니다! 현재 커리큘럼을 유지하며 다음 단계로 이어가세요.",
    coachx_days_ago_label: "마지막 레슨",
    // Members overview summary
    coachx_members_overview_title: "회원 성장 현황 요약",
    coachx_members_avg_score: "평균 성장 점수",
    coachx_members_top_score: "최고 점수: {name} ({score}점)",
    coachx_member_search_placeholder: "회원 이름 검색...",
    coachx_member_search_empty: "검색 결과가 없습니다.",
    // LessonCard
    media_load_error: "미디어를 불러올 수 없음",
    record_type_round: "라운드",
    record_type_lesson_rec: "레슨 기록",
    record_type_practice: "연습",
    feedback_requested: "피드백 요청",
    feedback_completed: "피드백 완료",
    media_hidden: "미디어 숨김",
    view_detail: "자세히 보기",
    // ReservationManager
    reservation_tab_slots: "슬롯 관리",
    reservation_tab_calendar: "캘린더",
    reservation_tab_settings: "근무 시간 설정",
    res_status_available: "예약 가능",
    res_status_blocked: "블럭됨",
    res_status_pending: "대기중",
    res_status_confirmed: "승인됨",
    res_status_cancelled: "취소됨",
    res_status_completed: "완료됨",
    slot_time_management: "시간 슬롯 관리",
    working_schedule_settings: "근무 요일 및 시간 설정",
    working_hours_outside_hint: "설정된 근무 시간 외의 슬롯은 회원에게 노출되지 않습니다.",
    approve_label: "승인",
    reject_label: "거부",
    release_label: "해제",
    confirm_approve_reservation: "이 예약을 승인하시겠습니까?",
    reservation_approved_msg: "예약이 승인되었습니다.",
    reservation_rejected_msg: "예약이 거부되었습니다.",
    reject_reason_prompt: "거부 사유를 입력해주세요 (선택사항):",
    confirm_cancel_reservation: "이 예약을 취소하시겠습니까?",
    reservation_cancelled_msg: "예약이 취소되었습니다.",
    working_hours_saved_msg: "근무 시간이 저장되었습니다.",
    saving_label: "저장 중...",
    save_working_hours: "근무 시간 저장",
    closed_day_label: "휴무",
    holiday_day_msg: "휴무일로 설정된 날입니다. 근무 시간 설정에서 변경할 수 있습니다.",
    reservation_count_all: "전체",
    no_reservations_label: "예약이 없습니다.",
    slot_change_failed_msg: "슬롯 변경에 실패했습니다.",
    approve_failed_msg: "승인에 실패했습니다.",
    reject_failed_msg: "거부에 실패했습니다.",
    cancel_failed_msg: "취소에 실패했습니다.",
    save_failed_msg: "저장에 실패했습니다.",
    register_label: "예약 등록",
    unavailable_label: "예약 불가",
    day_sun: "일",
    day_mon: "월",
    day_tue: "화",
    day_wed: "수",
    day_thu: "목",
    day_fri: "금",
    day_sat: "토",
    // ClientProfileSettings
    my_profile_title: "내 정보 설정",
    golf_profile_section: "골프 프로필",
    golf_experience_label: "구력 (경력)",
    handicap_label: "핸디캡",
    best_score_label: "라베 (Best Score)",
    bio_label: "자기소개 / 목표",
    club_bag_section: "사용 클럽 (백 구성)",
    no_clubs_registered: "등록된 클럽이 없습니다.",
    club_brand_placeholder: "브랜드 (예: 타이틀리스트)",
    club_model_placeholder: "모델명 (예: TSi3)",
    confirm_remove_coach: "담당 코치 지정을 해제하시겠습니까?",
    confirm_delete_club: "이 클럽을 삭제하시겠습니까?",
    exp_years_unit: "년",
    exp_months_unit: "개월",
    stats_based_analysis: "기록 기반 분석 ({n}게임)",
    club_category_driver: "드라이버",
    club_category_wood: "우드/유틸",
    club_category_iron: "아이언",
    club_category_wedge: "웨지",
    club_category_putter: "퍼터",
    driver_spec1: "로프트 (도)",
    driver_spec2: "샤프트/강도",
    wood_spec1: "번호/로프트",
    wood_spec2: "샤프트/강도",
    iron_spec1: "구성 (예: 5-P)",
    iron_spec2: "샤프트",
    wedge_spec1: "로프트 (도)",
    wedge_spec2: "바운스/샤프트",
    putter_spec1: "길이 (인치)",
    putter_spec2: "타입 (블레이드/말렛)",
    spec1_generic: "스펙 1",
    spec2_generic: "스펙 2",
    // HomeworkModal
    homework_modal_title: "숙제 관리 ({name}님)",
    homework_tab_list: "과제 현황 & 체크",
    homework_tab_assign: "새 과제 등록",
    homework_stats_title: "수행 현황 리포트",
    homework_stats_count: "총 {total}개 중 {completed}개 완료",
    homework_task_list_title: "과제 리스트",
    homework_empty: "과제 내역이 없습니다.",
    homework_done_confirmed: "완료 확인됨",
    homework_task_label: "과제 내용",
    homework_start_date: "시작일",
    homework_duration: "기간 설정",
    homework_days_select: "반복 요일 선택",
    homework_times_per_week: "주 {n}회",
    homework_total_label: "총 생성될 과제 수",
    homework_total_count_unit: "{n}개",
    homework_assign_btn: "과제 일괄 등록하기",
    homework_template_placeholder: "템플릿...",
    homework_placeholder: "예: 드라이버 빈스윙 20회",
    hw_motivation_high: "아주 훌륭합니다! 🏆",
    hw_motivation_mid: "꾸준히 하고 있어요 👍",
    hw_motivation_low: "조금 더 분발이 필요해요 💪",
    hw_validation_no_content: "과제 내용을 입력해주세요.",
    hw_validation_select_day: "요일을 최소 하루 이상 선택해주세요.",
    hw_no_dates_generated: "선택한 기간과 요일에 해당하는 날짜가 없습니다.",
    hw_assign_success: "{name}님에게 총 {count}개의 과제를 등록했습니다.",
    hw_assign_error: "과제 등록 중 오류가 발생했습니다.",
    hw_confirm_delete: "이 과제를 삭제하시겠습니까?",
    close_label: "닫기",
    duration_1w: "1주 (7일)",
    duration_2w: "2주 (14일)",
    duration_4w: "4주 (1개월)",
    duration_8w: "8주 (2개월)",
    duration_12w: "12주 (3개월)",
  },
  en: {
    // Auth
    app_desc: "Golf Lesson Analysis & Management Platform",
    coach_login: "Coach Login",
    client_login: "Member Login",
    admin_login: "Admin Login",
    email: "Email",
    password: "Password",
    name: "Name",
    phone: "Phone Number",
    phone_desc: "*Please enter exact number to link records.",
    auto_login: "Auto Login",
    login_btn: "Log In",
    signup_btn: "Sign Up",
    signup_msg: "No account? Sign up",
    login_msg: "Have an account? Log in",
    admin_only: "System Administrator Access Only.",
    find_account: "Find ID/Password",
    find_email_title: "Find Email",
    find_pw_title: "Find Password",
    find_btn: "Find",
    result_email: "Your email address is:",
    result_pw: "Your password is:",
    not_found: "No matching account found.",
    // Common
    logout: "Log Out",
    cancel: "Cancel",
    save: "Save",
    confirm: "Confirm",
    delete: "Delete",
    edit: "Edit",
    back: "Back",
    loading: "Loading...",
    // Coach Dashboard
    coach_dashboard: "Lesson Dashboard",
    coach_dashboard_desc: "Manage and record student lessons.",
    start_lesson: "Start Lesson",
    reservation_management: "Reservations",
    no_lessons: "No lessons recorded",
    no_lessons_desc: "Click 'Start Lesson' to record your first lesson.",
    // Client Dashboard
    today_mission: "Today's Mission",
    no_mission_today: "No tasks scheduled for today.",
    mission_manage: "Manage",
    ai_recommend: "AI Suggest",
    stats: "Statistics",
    my_info: "My Profile",
    recent_records: "Recent Records",
    no_records: "No records yet",
    no_records_desc: "Record your first practice or lesson!",
    // Roles
    coach: "Pro",
    client: "Member",
    // CoachX
    coachx_subtitle: "AI Golf Coaching Intelligence",
    coachx_entry_label: "Open CoachX",
    coachx_entry_desc: "AI Insights & Coaching Hub",
    coachx_tab_insights: "Insights",
    coachx_tab_members: "Member Growth",
    coachx_tab_curriculum: "Curriculum",
    coachx_stat_lessons: "Lessons",
    coachx_stat_members: "Members",
    coachx_stat_improving: "Improving",
    coachx_stat_attention: "Needs Attention",
    coachx_ask_title: "Ask CoachX",
    coachx_ask_desc: "Data-driven AI coaching assistant",
    coachx_insights_section: "Today's CoachX Insights",
    coachx_attention_label: "Members Needing Attention",
    coachx_stagnation_watch: "Growth Watch",
    coachx_no_members: "No lesson records yet. Start recording lessons!",
    coachx_curriculum_section: "Recommended Curriculum & Coach Growth",
    coachx_per_member_curriculum: "Per-Member Curriculum",
    coachx_suggested_prompts: "Suggested prompts",
    coachx_chat_placeholder: "Ask CoachX anything...",
    // MemberReportCard
    coachx_trend_improving: "Improving",
    coachx_trend_plateau: "Plateau",
    coachx_trend_new: "Getting Started",
    coachx_trend_inactive: "Inactive",
    coachx_lesson_count: "{n} lessons",
    coachx_days_ago: "{n}d ago",
    coachx_attention_high: "Needs Focus",
    coachx_attention_medium: "In Progress",
    coachx_attention_low: "Steady",
    coachx_section_report: "Growth Report",
    coachx_section_curriculum: "Curriculum",
    coachx_section_drills: "Drills",
    coachx_repeated_issues: "Potential Teaching Opportunities",
    coachx_strengths: "Developing Areas",
    coachx_suggested_focus: "Suggested Next Focus",
    coachx_plateau_tip: "This member may benefit from a fresh approach or a new drill to break through this development area.",
    coachx_inactive_tip: "It's been a while since the last lesson. A re-engagement session or goal reset could be helpful.",
    coachx_curriculum_5_sessions: "Suggested 5-Session Curriculum",
    coachx_drill_suggestions: "Helpful Practice Drills",
    coachx_suggested_drills_short: "Suggested Drills",
    coachx_drills_note: "Adjust drills to suit the member's current skill level and comfort.",
    // Coach Growth tab
    coachx_tab_coach_growth: "Coach Growth",
    coachx_growth_activity_title: "Teaching Activity",
    coachx_growth_this_month: "This Month",
    coachx_growth_last_month: "Last Month",
    coachx_growth_active_members: "Active Members",
    coachx_growth_avg_sessions: "Avg Sessions",
    coachx_growth_topic_breakdown: "Topic Analysis",
    coachx_growth_teaching_strengths: "Teaching Strengths",
    coachx_growth_opportunities: "Growth Opportunities",
    coachx_growth_recommended_actions: "Recommended Actions",
    coachx_growth_member_snapshot: "Member Progress Snapshot",
    coachx_growth_no_data: "Record lessons to unlock coach growth analysis.",
    coachx_growth_lessons_unit: "lessons",
    coachx_growth_sessions_unit: "sessions",
    coachx_growth_trend_improving: "Improving",
    coachx_growth_trend_plateau: "Plateau",
    coachx_growth_trend_new: "Getting Started",
    coachx_growth_trend_inactive: "Inactive",
    coachx_growth_opportunities_all_covered: "Teaching a great variety! 🎉",
    coachx_growth_topic_count: "{n} ({pct}%)",
    coachx_growth_vs_prev: "vs prev",
    coachx_growth_ai_summary_title: "AI Coach Growth Analysis",
    coachx_growth_ai_summary_loading: "AI is generating your coaching growth analysis…",
    // CoachX Live tab (inside CoachX Hub)
    coachx_tab_live: "Live",
    coachx_live_section_title: "CoachX Live",
    coachx_live_today_sessions: "Today's Sessions",
    coachx_live_today_sessions_count: "{n} recorded",
    coachx_live_no_sessions_today: "No sessions recorded today.",
    coachx_live_member_status: "Member Status",
    coachx_live_action_items: "Immediate Actions",
    coachx_live_no_actions: "All members are progressing well! 🎉",
    coachx_live_inactive_action: "{name} — A re-engagement lesson is recommended.",
    coachx_live_plateau_action: "{name} — A breakthrough focus session is recommended.",
    coachx_live_recent_activity: "Recent Activity",
    coachx_live_ask_coachx: "Ask CoachX",
    coachx_live_no_data: "Record lessons to activate the live status view.",
    // CoachX Preview Strip (home)
    coachx_preview_title: "CoachX Live Snapshot",
    coachx_preview_view_all: "View all",
    coachx_preview_open_label: "Open CoachX Hub",
    coachx_preview_improving: "improving",
    coachx_preview_plateau: "plateau",
    coachx_preview_inactive: "inactive",
    coachx_preview_new: "new",
    coachx_preview_urgency_suffix: "— focused care or a re-engagement session is recommended.",
    // CoachX Member History tab
    coachx_section_history: "History",
    coachx_history_monthly_activity: "Monthly Activity",
    coachx_history_recent_lessons: "Recent Lessons",
    coachx_history_empty: "No lesson history yet.",
    coachx_history_untitled: "Lesson",
    coachx_ask_about_member: "Ask CoachX about {name}",
    // CoachX urgency badge (home entry button)
    coachx_urgency_n_members: "{n} members need attention",
    coachx_urgency_one_member: "1 member needs attention",
    // CoachX integration in client list
    coachx_client_ask_coachx: "CoachX Analysis",
    // PR #108 – member growth detail screen
    coachx_view_full_report: "Full Report",
    coachx_growth_score_label: "Growth Score",
    coachx_growth_score_breakdown: "Growth Score",
    coachx_growth_score_desc: "Composite score based on lesson frequency, issue resolution, trend direction, and cadence.",
    coachx_issue_resolution_rate: "Issue Resolution Rate",
    coachx_issue_resolution_desc: "Percentage of early-lesson recurring issues no longer appearing in recent sessions.",
    coachx_lesson_cadence_title: "Lesson Cadence",
    coachx_cadence_avg_days: "Avg. interval (days)",
    coachx_cadence_value: "Average interval between lessons: {n} days",
    coachx_cadence_excellent: "Excellent",
    coachx_cadence_good: "Good",
    coachx_cadence_moderate: "Moderate",
    coachx_cadence_low: "Irregular",
    coachx_cadence_insufficient_data: "Insufficient data",
    coachx_weekly_activity_title: "Lesson Activity (Last 8 Weeks)",
    coachx_growth_metrics_title: "Growth Metrics",
    coachx_topic_progression_title: "Topic Progression",
    coachx_topic_early: "Early Lessons",
    coachx_topic_recent: "Recent Lessons",
    coachx_topic_no_data: "No data",
    coachx_topic_resolved: "Resolved",
    coachx_topic_ongoing: "Ongoing",
    coachx_topic_new_focus: "New focus",
    coachx_topic_progression_empty: "Not enough lesson data to show topic progression yet.",
    coachx_detail_summary_title: "Coaching Summary",
    coachx_detail_summary_improving: "This member is making consistent progress. Recent lessons show expanding focus areas and signs of growth. Keep the momentum and move to the next development stage.",
    coachx_detail_summary_plateau: "The same topics keep coming up in recent lessons. Introducing a fresh drill or shifting focus to a new area can help break through this plateau.",
    coachx_detail_summary_inactive: "It has been a while since the last lesson. A re-engagement message or a short goal-reset session can help reconnect.",
    coachx_detail_summary_new: "This member is just getting started. Building strong fundamentals now will accelerate long-term progress. Consistent lessons make all the difference.",
    coachx_detail_actions_title: "Recommended Coaching Actions",
    coachx_detail_action_reengage: "Send a re-engagement message or schedule a goal-reset session.",
    coachx_detail_action_fresh_approach: "Try a new drill approach or shift focus to a different topic to break through the plateau.",
    coachx_detail_action_increase_cadence: "Shorter intervals between lessons accelerate progress. Aim for at least weekly sessions.",
    coachx_detail_action_resolve_issues: "Intensify drill work on recurring issues to reach resolution.",
    coachx_detail_action_next_focus: "Make {topic} the primary focus of the next lesson.",
    coachx_detail_action_keep_momentum: "Great momentum! Maintain the current curriculum and advance to the next stage.",
    coachx_days_ago_label: "Last lesson",
    // Members overview summary
    coachx_members_overview_title: "Member Growth Overview",
    coachx_members_avg_score: "Avg. Growth Score",
    coachx_members_top_score: "Top score: {name} ({score}pts)",
    coachx_member_search_placeholder: "Search member name...",
    coachx_member_search_empty: "No members match your search.",
    // LessonCard
    media_load_error: "Media unavailable",
    record_type_round: "Round",
    record_type_lesson_rec: "Lesson",
    record_type_practice: "Practice",
    feedback_requested: "Feedback Requested",
    feedback_completed: "Feedback Done",
    media_hidden: "Media Hidden",
    view_detail: "View Detail",
    // ReservationManager
    reservation_tab_slots: "Slot Management",
    reservation_tab_calendar: "Calendar",
    reservation_tab_settings: "Work Hours",
    res_status_available: "Available",
    res_status_blocked: "Blocked",
    res_status_pending: "Pending",
    res_status_confirmed: "Confirmed",
    res_status_cancelled: "Cancelled",
    res_status_completed: "Completed",
    slot_time_management: "Time Slot Management",
    working_schedule_settings: "Work Schedule",
    working_hours_outside_hint: "Slots outside working hours won't be visible to members.",
    approve_label: "Approve",
    reject_label: "Reject",
    release_label: "Release",
    confirm_approve_reservation: "Approve this reservation?",
    reservation_approved_msg: "Reservation approved.",
    reservation_rejected_msg: "Reservation rejected.",
    reject_reason_prompt: "Enter rejection reason (optional):",
    confirm_cancel_reservation: "Cancel this reservation?",
    reservation_cancelled_msg: "Reservation cancelled.",
    working_hours_saved_msg: "Working hours saved.",
    saving_label: "Saving...",
    save_working_hours: "Save Working Hours",
    closed_day_label: "Closed",
    holiday_day_msg: "This is a closed day. Change in Work Hours settings.",
    reservation_count_all: "All",
    no_reservations_label: "No reservations.",
    slot_change_failed_msg: "Failed to update slot.",
    approve_failed_msg: "Approval failed.",
    reject_failed_msg: "Rejection failed.",
    cancel_failed_msg: "Cancellation failed.",
    save_failed_msg: "Save failed.",
    register_label: "Register",
    unavailable_label: "Unavailable",
    day_sun: "Sun",
    day_mon: "Mon",
    day_tue: "Tue",
    day_wed: "Wed",
    day_thu: "Thu",
    day_fri: "Fri",
    day_sat: "Sat",
    // ClientProfileSettings
    my_profile_title: "My Profile",
    golf_profile_section: "Golf Profile",
    golf_experience_label: "Experience",
    handicap_label: "Handicap",
    best_score_label: "Best Score",
    bio_label: "Bio / Goal",
    club_bag_section: "My Club Bag",
    no_clubs_registered: "No clubs registered.",
    club_brand_placeholder: "Brand (e.g. Titleist)",
    club_model_placeholder: "Model (e.g. TSi3)",
    confirm_remove_coach: "Remove designated coach?",
    confirm_delete_club: "Delete this club?",
    exp_years_unit: "yr",
    exp_months_unit: "mo",
    stats_based_analysis: "Record Analysis ({n} games)",
    club_category_driver: "Driver",
    club_category_wood: "Wood/Hybrid",
    club_category_iron: "Iron",
    club_category_wedge: "Wedge",
    club_category_putter: "Putter",
    driver_spec1: "Loft (°)",
    driver_spec2: "Shaft/Flex",
    wood_spec1: "Club#/Loft",
    wood_spec2: "Shaft/Flex",
    iron_spec1: "Set (e.g. 5-P)",
    iron_spec2: "Shaft",
    wedge_spec1: "Loft (°)",
    wedge_spec2: "Bounce/Shaft",
    putter_spec1: "Length (in)",
    putter_spec2: "Type (Blade/Mallet)",
    spec1_generic: "Spec 1",
    spec2_generic: "Spec 2",
    // HomeworkModal
    homework_modal_title: "Homework ({name})",
    homework_tab_list: "Task Status",
    homework_tab_assign: "New Task",
    homework_stats_title: "Progress Report",
    homework_stats_count: "{completed} of {total} completed",
    homework_task_list_title: "Task List",
    homework_empty: "No homework yet.",
    homework_done_confirmed: "Done",
    homework_task_label: "Task",
    homework_start_date: "Start Date",
    homework_duration: "Duration",
    homework_days_select: "Select Days",
    homework_times_per_week: "{n}x/week",
    homework_total_label: "Total Tasks",
    homework_total_count_unit: "{n} tasks",
    homework_assign_btn: "Assign Homework",
    homework_template_placeholder: "Template...",
    homework_placeholder: "e.g. 20 air swings",
    hw_motivation_high: "Excellent! 🏆",
    hw_motivation_mid: "Keeping it up 👍",
    hw_motivation_low: "Keep pushing 💪",
    hw_validation_no_content: "Please enter task content.",
    hw_validation_select_day: "Select at least one day.",
    hw_no_dates_generated: "No dates match the selected period and days.",
    hw_assign_success: "Assigned {count} tasks to {name}.",
    hw_assign_error: "Error assigning homework.",
    hw_confirm_delete: "Delete this task?",
    close_label: "Close",
    duration_1w: "1 week (7 days)",
    duration_2w: "2 weeks (14 days)",
    duration_4w: "4 weeks (1 month)",
    duration_8w: "8 weeks (2 months)",
    duration_12w: "12 weeks (3 months)",
  },
  ja: {
    // Auth
    app_desc: "ゴルフレッスン分析・管理プラットフォーム",
    coach_login: "コーチログイン",
    client_login: "会員ログイン",
    admin_login: "管理者ログイン",
    email: "メールアドレス",
    password: "パスワード",
    name: "名前",
    phone: "電話番号",
    phone_desc: "*記録連携のため正確な番号を入力してください。",
    auto_login: "自動ログイン",
    login_btn: "ログイン",
    signup_btn: "会員登録",
    signup_msg: "アカウントをお持ちでないですか？登録",
    login_msg: "すでにアカウントをお持ちですか？ログイン",
    admin_only: "システム管理者専用ページです。",
    find_account: "ID/パスワード検索",
    find_email_title: "メールアドレス検索",
    find_pw_title: "パスワード検索",
    find_btn: "検索",
    result_email: "あなたのメールアドレスは:",
    result_pw: "あなたのパスワードは:",
    not_found: "一致するアカウントが見つかりません。",
    // Common
    logout: "ログアウト",
    cancel: "キャンセル",
    save: "保存",
    confirm: "確認",
    delete: "削除",
    edit: "修正",
    back: "戻る",
    loading: "読み込み中...",
    // Coach Dashboard
    coach_dashboard: "レッスン管理",
    coach_dashboard_desc: "会員のレッスンを記録・管理します。",
    start_lesson: "レッスン開始",
    reservation_management: "予約管理",
    no_lessons: "記録されたレッスンがありません",
    no_lessons_desc: "'レッスン開始'ボタンを押して記録してください。",
    // Client Dashboard
    today_mission: "今日のミッション",
    no_mission_today: "今日の課題はありません。",
    mission_manage: "管理",
    ai_recommend: "AI推奨",
    stats: "データ統計",
    my_info: "設定",
    recent_records: "最近の記録",
    no_records: "記録がありません",
    no_records_desc: "最初の練習やレッスンを記録しましょう！",
    // Roles
    coach: "プロ",
    client: "会員",
    // CoachX
    coachx_subtitle: "AIゴルフコーチングインテリジェンス",
    coachx_entry_label: "CoachXを開く",
    coachx_entry_desc: "AIインサイト & コーチングハブ",
    coachx_tab_insights: "インサイト",
    coachx_tab_members: "会員成長",
    coachx_tab_curriculum: "カリキュラム",
    coachx_stat_lessons: "レッスン記録",
    coachx_stat_members: "担当会員",
    coachx_stat_improving: "成長中",
    coachx_stat_attention: "要注意",
    coachx_ask_title: "CoachXに質問する",
    coachx_ask_desc: "データ基盤のAIコーチングアシスタント",
    coachx_insights_section: "今日のCoachXインサイト",
    coachx_attention_label: "注意が必要な会員",
    coachx_stagnation_watch: "成長要観察会員",
    coachx_no_members: "レッスン記録がありません。最初のレッスンを記録しましょう！",
    coachx_curriculum_section: "推奨カリキュラム & コーチ成長",
    coachx_per_member_curriculum: "会員別推奨カリキュラム",
    coachx_suggested_prompts: "おすすめの質問",
    coachx_chat_placeholder: "CoachXに質問してください...",
    // MemberReportCard
    coachx_trend_improving: "成長中",
    coachx_trend_plateau: "停滞期",
    coachx_trend_new: "開始段階",
    coachx_trend_inactive: "長期未レッスン",
    coachx_lesson_count: "レッスン{n}回",
    coachx_days_ago: "{n}日前",
    coachx_attention_high: "集中ケア必要",
    coachx_attention_medium: "進行中",
    coachx_attention_low: "安定",
    coachx_section_report: "成長レポート",
    coachx_section_curriculum: "カリキュラム",
    coachx_section_drills: "推奨ドリル",
    coachx_repeated_issues: "繰り返し教正ポイント",
    coachx_strengths: "強化されたエリア",
    coachx_suggested_focus: "次のレッスン推奨フォーカス",
    coachx_plateau_tip: "同じ課題が繰り返されています。新しいアプローチや別のテーマへの転換を検討してください。",
    coachx_inactive_tip: "最後のレッスンから時間が経っています。再参加メッセージや目標再設定レッスンをお勧めします。",
    coachx_curriculum_5_sessions: "推奨5回カリキュラム",
    coachx_drill_suggestions: "推奨練習ドリル",
    coachx_suggested_drills_short: "推奨ドリル",
    coachx_drills_note: "ドリルは会員の現在のレベルに合わせて調整してください。",
    // Coach Growth tab
    coachx_tab_coach_growth: "コーチ成長",
    coachx_growth_activity_title: "指導活動状況",
    coachx_growth_this_month: "今月",
    coachx_growth_last_month: "先月",
    coachx_growth_active_members: "アクティブ会員",
    coachx_growth_avg_sessions: "平均レッスン",
    coachx_growth_topic_breakdown: "指導テーマ分析",
    coachx_growth_teaching_strengths: "指導強み領域",
    coachx_growth_opportunities: "成長機会領域",
    coachx_growth_recommended_actions: "推奨アクション",
    coachx_growth_member_snapshot: "会員成長スナップショット",
    coachx_growth_no_data: "レッスンを記録するとコーチ成長分析が表示されます。",
    coachx_growth_lessons_unit: "レッスン",
    coachx_growth_sessions_unit: "回",
    coachx_growth_trend_improving: "成長中",
    coachx_growth_trend_plateau: "停滞期",
    coachx_growth_trend_new: "開始段階",
    coachx_growth_trend_inactive: "未レッスン",
    coachx_growth_opportunities_all_covered: "様々な分野を指導しています！ 🎉",
    coachx_growth_topic_count: "{n}回 ({pct}%)",
    coachx_growth_vs_prev: "前月比",
    coachx_growth_ai_summary_title: "AI コーチ成長分析",
    coachx_growth_ai_summary_loading: "AIがコーチ成長分析を生成中です…",
    // CoachX Live tab (inside CoachX Hub)
    coachx_tab_live: "ライブ",
    coachx_live_section_title: "CoachX ライブ現況",
    coachx_live_today_sessions: "今日のレッスン",
    coachx_live_today_sessions_count: "{n}件記録",
    coachx_live_no_sessions_today: "今日のレッスンはまだ記録されていません。",
    coachx_live_member_status: "会員状況",
    coachx_live_action_items: "即時アクション",
    coachx_live_no_actions: "すべての会員が順調に成長中です！ 🎉",
    coachx_live_inactive_action: "{name} — 再参加レッスンをお勧めします。",
    coachx_live_plateau_action: "{name} — 停滞打破の集中レッスンをお勧めします。",
    coachx_live_recent_activity: "最近の活動",
    coachx_live_ask_coachx: "CoachXに聞く",
    coachx_live_no_data: "レッスンを記録するとライブ現況が表示されます。",
    // CoachX Preview Strip (home)
    coachx_preview_title: "CoachX ライブ状況",
    coachx_preview_view_all: "すべて見る",
    coachx_preview_open_label: "CoachXハブを開く",
    coachx_preview_improving: "成長中",
    coachx_preview_plateau: "停滞期",
    coachx_preview_inactive: "未レッスン",
    coachx_preview_new: "新規",
    coachx_preview_urgency_suffix: "— 集中ケアまたは再参加レッスンをお勧めします。",
    // CoachX Member History tab
    coachx_section_history: "レッスン履歴",
    coachx_history_monthly_activity: "月別レッスン",
    coachx_history_recent_lessons: "最近のレッスン",
    coachx_history_empty: "レッスン記録はまだありません。",
    coachx_history_untitled: "レッスン",
    coachx_ask_about_member: "{name}についてCoachXに聞く",
    // CoachX urgency badge (home entry button)
    coachx_urgency_n_members: "{n}名 集中ケア必要",
    coachx_urgency_one_member: "1名 集中ケア必要",
    // CoachX integration in client list
    coachx_client_ask_coachx: "CoachX分析",
    // PR #108 – member growth detail screen
    coachx_view_full_report: "詳細レポート",
    coachx_growth_score_label: "成長スコア",
    coachx_growth_score_breakdown: "成長スコア",
    coachx_growth_score_desc: "レッスン頻度・課題解決率・成長傾向・レッスン周期の総合スコアです。",
    coachx_issue_resolution_rate: "課題解決率",
    coachx_issue_resolution_desc: "初期レッスンの繰り返し課題のうち、最近のレッスンで解決された割合です。",
    coachx_lesson_cadence_title: "レッスン周期",
    coachx_cadence_avg_days: "平均間隔（日）",
    coachx_cadence_value: "レッスン平均間隔: {n}日",
    coachx_cadence_excellent: "非常に規則的",
    coachx_cadence_good: "規則的",
    coachx_cadence_moderate: "普通",
    coachx_cadence_low: "不規則",
    coachx_cadence_insufficient_data: "データ不足",
    coachx_weekly_activity_title: "直近8週間のレッスン活動",
    coachx_growth_metrics_title: "成長指標",
    coachx_topic_progression_title: "指導テーマの変化",
    coachx_topic_early: "初期レッスン",
    coachx_topic_recent: "最近のレッスン",
    coachx_topic_no_data: "データなし",
    coachx_topic_resolved: "解決済み",
    coachx_topic_ongoing: "継続中",
    coachx_topic_new_focus: "新テーマ",
    coachx_topic_progression_empty: "テーマ変化を分析するにはもう少しレッスン記録が必要です。",
    coachx_detail_summary_title: "コーチングサマリー",
    coachx_detail_summary_improving: "着実に成長しています。最近のレッスンでは幅広い分野を取り扱っており、進歩の兆しが見えます。この流れを維持して次のステージへ進みましょう。",
    coachx_detail_summary_plateau: "最近のレッスンで同じテーマが繰り返されています。新しいドリルや別のテーマへの転換が停滞突破に役立ちます。",
    coachx_detail_summary_inactive: "最後のレッスンから時間が経過しています。再参加メッセージや目標リセットレッスンで再接続を試みましょう。",
    coachx_detail_summary_new: "まだ始まったばかりです。基礎をしっかり固めることが長期的な成長を加速します。定期的なレッスンが大切です。",
    coachx_detail_actions_title: "推奨コーチングアクション",
    coachx_detail_action_reengage: "再参加メッセージを送るか、目標リセットレッスンを予約しましょう。",
    coachx_detail_action_fresh_approach: "新しいドリルを試すか、別のテーマに転換して停滞を打破しましょう。",
    coachx_detail_action_increase_cadence: "レッスン間隔を短くすると成長が加速します。週1回以上のレッスンを目標にしましょう。",
    coachx_detail_action_resolve_issues: "繰り返す課題に集中してドリルを強化し、解決に導きましょう。",
    coachx_detail_action_next_focus: "{topic} を次のレッスンの主要テーマにしましょう。",
    coachx_detail_action_keep_momentum: "素晴らしい流れです！現在のカリキュラムを維持して次のステージへ進みましょう。",
    coachx_days_ago_label: "最終レッスン",
    // Members overview summary
    coachx_members_overview_title: "会員成長状況サマリー",
    coachx_members_avg_score: "平均成長スコア",
    coachx_members_top_score: "最高スコア: {name}（{score}点）",
    coachx_member_search_placeholder: "会員名を検索...",
    coachx_member_search_empty: "検索結果がありません。",
    // LessonCard
    media_load_error: "メディアを読み込めません",
    record_type_round: "ラウンド",
    record_type_lesson_rec: "レッスン記録",
    record_type_practice: "練習",
    feedback_requested: "フィードバック依頼",
    feedback_completed: "フィードバック完了",
    media_hidden: "メディア非表示",
    view_detail: "詳細を見る",
    // ReservationManager
    reservation_tab_slots: "スロット管理",
    reservation_tab_calendar: "カレンダー",
    reservation_tab_settings: "勤務時間設定",
    res_status_available: "予約可能",
    res_status_blocked: "ブロック",
    res_status_pending: "保留中",
    res_status_confirmed: "承認済み",
    res_status_cancelled: "キャンセル済",
    res_status_completed: "完了",
    slot_time_management: "時間スロット管理",
    working_schedule_settings: "勤務スケジュール設定",
    working_hours_outside_hint: "勤務時間外のスロットは会員に表示されません。",
    approve_label: "承認",
    reject_label: "拒否",
    release_label: "解除",
    confirm_approve_reservation: "この予約を承認しますか？",
    reservation_approved_msg: "予約が承認されました。",
    reservation_rejected_msg: "予約が拒否されました。",
    reject_reason_prompt: "拒否理由を入力してください（任意）:",
    confirm_cancel_reservation: "この予約をキャンセルしますか？",
    reservation_cancelled_msg: "予約がキャンセルされました。",
    working_hours_saved_msg: "勤務時間が保存されました。",
    saving_label: "保存中...",
    save_working_hours: "勤務時間を保存",
    closed_day_label: "休業",
    holiday_day_msg: "休業日に設定されています。勤務時間設定で変更できます。",
    reservation_count_all: "全て",
    no_reservations_label: "予約がありません。",
    slot_change_failed_msg: "スロット変更に失敗しました。",
    approve_failed_msg: "承認に失敗しました。",
    reject_failed_msg: "拒否に失敗しました。",
    cancel_failed_msg: "キャンセルに失敗しました。",
    save_failed_msg: "保存に失敗しました。",
    register_label: "予約登録",
    unavailable_label: "予約不可",
    day_sun: "日",
    day_mon: "月",
    day_tue: "火",
    day_wed: "水",
    day_thu: "木",
    day_fri: "金",
    day_sat: "土",
    // ClientProfileSettings
    my_profile_title: "プロフィール設定",
    golf_profile_section: "ゴルフプロフィール",
    golf_experience_label: "ゴルフ歴",
    handicap_label: "ハンディキャップ",
    best_score_label: "ベストスコア",
    bio_label: "自己紹介 / 目標",
    club_bag_section: "クラブセット",
    no_clubs_registered: "クラブが登録されていません。",
    club_brand_placeholder: "ブランド（例: タイトリスト）",
    club_model_placeholder: "モデル名（例: TSi3）",
    confirm_remove_coach: "担当コーチの指定を解除しますか？",
    confirm_delete_club: "このクラブを削除しますか？",
    exp_years_unit: "年",
    exp_months_unit: "ヶ月",
    stats_based_analysis: "記録ベース分析 ({n}ゲーム)",
    club_category_driver: "ドライバー",
    club_category_wood: "ウッド/ユーティリティ",
    club_category_iron: "アイアン",
    club_category_wedge: "ウェッジ",
    club_category_putter: "パター",
    driver_spec1: "ロフト（度）",
    driver_spec2: "シャフト/強度",
    wood_spec1: "番号/ロフト",
    wood_spec2: "シャフト/強度",
    iron_spec1: "構成（例: 5-P）",
    iron_spec2: "シャフト",
    wedge_spec1: "ロフト（度）",
    wedge_spec2: "バウンス/シャフト",
    putter_spec1: "長さ（インチ）",
    putter_spec2: "タイプ（ブレード/マレット）",
    spec1_generic: "スペック1",
    spec2_generic: "スペック2",
    // HomeworkModal
    homework_modal_title: "宿題管理 ({name}さん)",
    homework_tab_list: "課題状況",
    homework_tab_assign: "新しい課題",
    homework_stats_title: "進捗レポート",
    homework_stats_count: "計{total}個中 {completed}個完了",
    homework_task_list_title: "課題リスト",
    homework_empty: "課題がありません。",
    homework_done_confirmed: "完了確認済",
    homework_task_label: "課題内容",
    homework_start_date: "開始日",
    homework_duration: "期間設定",
    homework_days_select: "繰り返し曜日",
    homework_times_per_week: "週{n}回",
    homework_total_label: "総課題数",
    homework_total_count_unit: "{n}個",
    homework_assign_btn: "課題を一括登録",
    homework_template_placeholder: "テンプレート...",
    homework_placeholder: "例: ドライバー素振り20回",
    hw_motivation_high: "非常に優秀です！🏆",
    hw_motivation_mid: "着実にやっています 👍",
    hw_motivation_low: "もう少し頑張りましょう 💪",
    hw_validation_no_content: "課題内容を入力してください。",
    hw_validation_select_day: "曜日を1日以上選択してください。",
    hw_no_dates_generated: "選択した期間と曜日に該当する日付がありません。",
    hw_assign_success: "{name}さんに計{count}個の課題を登録しました。",
    hw_assign_error: "課題登録中にエラーが発生しました。",
    hw_confirm_delete: "この課題を削除しますか？",
    close_label: "閉じる",
    duration_1w: "1週間 (7日)",
    duration_2w: "2週間 (14日)",
    duration_4w: "4週間 (1ヶ月)",
    duration_8w: "8週間 (2ヶ月)",
    duration_12w: "12週間 (3ヶ月)",
  },
  th: {
    // Auth
    app_desc: "แพลตฟอร์มวิเคราะห์และจัดการบทเรียนกอล์ฟ",
    coach_login: "เข้าสู่ระบบโค้ช",
    client_login: "เข้าสู่ระบบสมาชิก",
    admin_login: "เข้าสู่ระบบผู้ดูแล",
    email: "อีเมล",
    password: "รหัสผ่าน",
    name: "ชื่อ",
    phone: "หมายเลขโทรศัพท์",
    phone_desc: "*กรุณากรอกหมายเลขที่ถูกต้องเพื่อเชื่อมบันทึก",
    auto_login: "เข้าสู่ระบบอัตโนมัติ",
    login_btn: "เข้าสู่ระบบ",
    signup_btn: "สมัครสมาชิก",
    signup_msg: "ยังไม่มีบัญชี? สมัครสมาชิก",
    login_msg: "มีบัญชีอยู่แล้ว? เข้าสู่ระบบ",
    admin_only: "สำหรับผู้ดูแลระบบเท่านั้น",
    find_account: "ค้นหา ID/รหัสผ่าน",
    find_email_title: "ค้นหาอีเมล",
    find_pw_title: "ค้นหารหัสผ่าน",
    find_btn: "ค้นหา",
    result_email: "อีเมลของคุณคือ:",
    result_pw: "รหัสผ่านของคุณคือ:",
    not_found: "ไม่พบข้อมูลที่ตรงกัน",
    // Common
    logout: "ออกจากระบบ",
    cancel: "ยกเลิก",
    save: "บันทึก",
    confirm: "ยืนยัน",
    delete: "ลบ",
    edit: "แก้ไข",
    back: "กลับ",
    loading: "กำลังโหลด...",
    // Coach Dashboard
    coach_dashboard: "แดชบอร์ดบทเรียน",
    coach_dashboard_desc: "จัดการและบันทึกบทเรียนของสมาชิก",
    start_lesson: "เริ่มบทเรียน",
    reservation_management: "จัดการการจอง",
    no_lessons: "ยังไม่มีบทเรียนที่บันทึก",
    no_lessons_desc: "กดปุ่ม 'เริ่มบทเรียน' เพื่อบันทึกบทเรียนแรก",
    // Client Dashboard
    today_mission: "ภารกิจวันนี้",
    no_mission_today: "ไม่มีภารกิจที่กำหนดวันนี้",
    mission_manage: "จัดการ",
    ai_recommend: "AI แนะนำ",
    stats: "สถิติ",
    my_info: "โปรไฟล์ของฉัน",
    recent_records: "บันทึกล่าสุด",
    no_records: "ยังไม่มีบันทึก",
    no_records_desc: "บันทึกการฝึกซ้อมหรือบทเรียนแรกของคุณ!",
    // Roles
    coach: "โปร",
    client: "สมาชิก",
    // CoachX
    coachx_subtitle: "ปัญญาประดิษฐ์การโค้ชกอล์ฟ",
    coachx_entry_label: "เปิด CoachX",
    coachx_entry_desc: "ข้อมูลเชิงลึก AI & ศูนย์การโค้ช",
    coachx_tab_insights: "ข้อมูลเชิงลึก",
    coachx_tab_members: "การเติบโตของสมาชิก",
    coachx_tab_curriculum: "หลักสูตร",
    coachx_stat_lessons: "บทเรียน",
    coachx_stat_members: "สมาชิก",
    coachx_stat_improving: "กำลังพัฒนา",
    coachx_stat_attention: "ต้องดูแลพิเศษ",
    coachx_ask_title: "ถาม CoachX",
    coachx_ask_desc: "ผู้ช่วยโค้ช AI จากข้อมูลจริง",
    coachx_insights_section: "ข้อมูลเชิงลึก CoachX วันนี้",
    coachx_attention_label: "สมาชิกที่ต้องดูแลพิเศษ",
    coachx_stagnation_watch: "สมาชิกที่ต้องติดตาม",
    coachx_no_members: "ยังไม่มีบันทึกบทเรียน เริ่มบันทึกบทเรียนแรก!",
    coachx_curriculum_section: "หลักสูตรแนะนำ & การเติบโตของโค้ช",
    coachx_per_member_curriculum: "หลักสูตรรายสมาชิก",
    coachx_suggested_prompts: "คำถามแนะนำ",
    coachx_chat_placeholder: "ถาม CoachX ได้เลย...",
    // MemberReportCard
    coachx_trend_improving: "กำลังพัฒนา",
    coachx_trend_plateau: "ติดขัด",
    coachx_trend_new: "เริ่มต้น",
    coachx_trend_inactive: "ไม่ได้เรียน",
    coachx_lesson_count: "{n} บทเรียน",
    coachx_days_ago: "{n} วันที่แล้ว",
    coachx_attention_high: "ต้องดูแลพิเศษ",
    coachx_attention_medium: "กำลังดำเนินการ",
    coachx_attention_low: "ปกติ",
    coachx_section_report: "รายงานการเติบโต",
    coachx_section_curriculum: "หลักสูตร",
    coachx_section_drills: "การฝึกซ้อมแนะนำ",
    coachx_repeated_issues: "จุดที่ต้องแก้ไขซ้ำ",
    coachx_strengths: "จุดแข็งที่พัฒนาแล้ว",
    coachx_suggested_focus: "ทิศทางบทเรียนถัดไป",
    coachx_plateau_tip: "มีปัญหาซ้ำเดิม ลองเปลี่ยนแนวทางหรือหัวข้อใหม่",
    coachx_inactive_tip: "ไม่ได้เรียนมานาน แนะนำให้ส่งข้อความหรือจัดบทเรียนตั้งเป้าหมายใหม่",
    coachx_curriculum_5_sessions: "หลักสูตร 5 ครั้งแนะนำ",
    coachx_drill_suggestions: "การฝึกซ้อมแนะนำ",
    coachx_suggested_drills_short: "ฝึกซ้อมแนะนำ",
    coachx_drills_note: "ปรับการฝึกซ้อมให้เหมาะกับระดับของสมาชิก",
    // Coach Growth tab
    coachx_tab_coach_growth: "การเติบโตของโค้ช",
    coachx_growth_activity_title: "กิจกรรมการสอน",
    coachx_growth_this_month: "เดือนนี้",
    coachx_growth_last_month: "เดือนที่แล้ว",
    coachx_growth_active_members: "สมาชิกที่ใช้งาน",
    coachx_growth_avg_sessions: "เฉลี่ยต่อสมาชิก",
    coachx_growth_topic_breakdown: "การวิเคราะห์หัวข้อ",
    coachx_growth_teaching_strengths: "จุดแข็งการสอน",
    coachx_growth_opportunities: "โอกาสพัฒนา",
    coachx_growth_recommended_actions: "การดำเนินการแนะนำ",
    coachx_growth_member_snapshot: "ภาพรวมการเติบโตของสมาชิก",
    coachx_growth_no_data: "บันทึกบทเรียนเพื่อดูการวิเคราะห์การเติบโตของโค้ช",
    coachx_growth_lessons_unit: "บทเรียน",
    coachx_growth_sessions_unit: "ครั้ง",
    coachx_growth_trend_improving: "กำลังพัฒนา",
    coachx_growth_trend_plateau: "ติดขัด",
    coachx_growth_trend_new: "เริ่มต้น",
    coachx_growth_trend_inactive: "ไม่ได้เรียน",
    coachx_growth_opportunities_all_covered: "สอนได้หลากหลายมาก! 🎉",
    coachx_growth_topic_count: "{n} ครั้ง ({pct}%)",
    coachx_growth_vs_prev: "เทียบเดือนก่อน",
    coachx_growth_ai_summary_title: "AI วิเคราะห์การเติบโตของโค้ช",
    coachx_growth_ai_summary_loading: "AI กำลังสร้างการวิเคราะห์...",
    // CoachX Live tab
    coachx_tab_live: "สด",
    coachx_live_section_title: "CoachX สถานะสด",
    coachx_live_today_sessions: "บทเรียนวันนี้",
    coachx_live_today_sessions_count: "บันทึก {n} รายการ",
    coachx_live_no_sessions_today: "ยังไม่มีบทเรียนที่บันทึกวันนี้",
    coachx_live_member_status: "สถานะสมาชิก",
    coachx_live_action_items: "การดำเนินการทันที",
    coachx_live_no_actions: "สมาชิกทุกคนกำลังพัฒนาได้ดี! 🎉",
    coachx_live_inactive_action: "{name} — แนะนำให้จัดบทเรียนกลับมา",
    coachx_live_plateau_action: "{name} — แนะนำบทเรียนเจาะลึกเพื่อฝ่าจุดติดขัด",
    coachx_live_recent_activity: "กิจกรรมล่าสุด",
    coachx_live_ask_coachx: "ถาม CoachX",
    coachx_live_no_data: "บันทึกบทเรียนเพื่อดูสถานะสด",
    // CoachX Preview Strip
    coachx_preview_title: "CoachX สถานะสด",
    coachx_preview_view_all: "ดูทั้งหมด",
    coachx_preview_open_label: "เปิด CoachX Hub",
    coachx_preview_improving: "กำลังพัฒนา",
    coachx_preview_plateau: "ติดขัด",
    coachx_preview_inactive: "ไม่ได้เรียน",
    coachx_preview_new: "ใหม่",
    coachx_preview_urgency_suffix: "— แนะนำดูแลพิเศษหรือบทเรียนกลับมา",
    // CoachX Member History tab
    coachx_section_history: "ประวัติบทเรียน",
    coachx_history_monthly_activity: "กิจกรรมรายเดือน",
    coachx_history_recent_lessons: "บทเรียนล่าสุด",
    coachx_history_empty: "ยังไม่มีประวัติบทเรียน",
    coachx_history_untitled: "บทเรียน",
    coachx_ask_about_member: "ถาม CoachX เกี่ยวกับ {name}",
    // CoachX urgency badge
    coachx_urgency_n_members: "{n} คนต้องดูแลพิเศษ",
    coachx_urgency_one_member: "1 คนต้องดูแลพิเศษ",
    // CoachX integration in client list
    coachx_client_ask_coachx: "วิเคราะห์ CoachX",
    // PR #108 – member growth detail screen
    coachx_view_full_report: "รายงานเต็ม",
    coachx_growth_score_label: "คะแนนการเติบโต",
    coachx_growth_score_breakdown: "คะแนนการเติบโต",
    coachx_growth_score_desc: "คะแนนรวมจากความถี่บทเรียน อัตราแก้ปัญหา แนวโน้ม และรอบการเรียน",
    coachx_issue_resolution_rate: "อัตราการแก้ปัญหา",
    coachx_issue_resolution_desc: "เปอร์เซ็นต์ของปัญหาซ้ำในบทเรียนแรกที่ไม่ปรากฏในบทเรียนล่าสุด",
    coachx_lesson_cadence_title: "รอบการเรียน",
    coachx_cadence_avg_days: "ระยะเฉลี่ย (วัน)",
    coachx_cadence_value: "ระยะห่างเฉลี่ยระหว่างบทเรียน: {n} วัน",
    coachx_cadence_excellent: "สม่ำเสมอมาก",
    coachx_cadence_good: "สม่ำเสมอ",
    coachx_cadence_moderate: "พอสมควร",
    coachx_cadence_low: "ไม่สม่ำเสมอ",
    coachx_cadence_insufficient_data: "ข้อมูลไม่เพียงพอ",
    coachx_weekly_activity_title: "กิจกรรมบทเรียน 8 สัปดาห์ที่ผ่านมา",
    coachx_growth_metrics_title: "ตัวชี้วัดการเติบโต",
    coachx_topic_progression_title: "การเปลี่ยนแปลงหัวข้อ",
    coachx_topic_early: "บทเรียนแรกๆ",
    coachx_topic_recent: "บทเรียนล่าสุด",
    coachx_topic_no_data: "ไม่มีข้อมูล",
    coachx_topic_resolved: "แก้ไขแล้ว",
    coachx_topic_ongoing: "กำลังดำเนินการ",
    coachx_topic_new_focus: "หัวข้อใหม่",
    coachx_topic_progression_empty: "ยังมีข้อมูลบทเรียนไม่เพียงพอสำหรับการวิเคราะห์หัวข้อ",
    coachx_detail_summary_title: "สรุปการโค้ช",
    coachx_detail_summary_improving: "สมาชิกกำลังพัฒนาอย่างต่อเนื่อง บทเรียนล่าสุดครอบคลุมหลายด้านและแสดงสัญญาณการเติบโต รักษาแรงผลักดันและก้าวสู่ขั้นต่อไป",
    coachx_detail_summary_plateau: "หัวข้อเดิมยังคงปรากฏในบทเรียนล่าสุด การนำการฝึกซ้อมใหม่หรือเปลี่ยนหัวข้อช่วยฝ่าจุดติดขัดได้",
    coachx_detail_summary_inactive: "ไม่ได้เรียนมาสักพักแล้ว การส่งข้อความหรือจัดบทเรียนตั้งเป้าหมายใหม่จะช่วยเชื่อมต่อกลับมา",
    coachx_detail_summary_new: "สมาชิกเพิ่งเริ่มต้น การสร้างรากฐานที่แข็งแกร่งตอนนี้จะเร่งความก้าวหน้าในระยะยาว",
    coachx_detail_actions_title: "การดำเนินการโค้ชแนะนำ",
    coachx_detail_action_reengage: "ส่งข้อความหรือจัดบทเรียนตั้งเป้าหมายใหม่",
    coachx_detail_action_fresh_approach: "ลองการฝึกซ้อมใหม่หรือเปลี่ยนหัวข้อเพื่อฝ่าจุดติดขัด",
    coachx_detail_action_increase_cadence: "ลดช่วงเวลาระหว่างบทเรียนเพื่อเร่งความก้าวหน้า แนะนำอย่างน้อยสัปดาห์ละครั้ง",
    coachx_detail_action_resolve_issues: "เน้นการฝึกซ้อมปัญหาซ้ำเพื่อแก้ไขให้ได้",
    coachx_detail_action_next_focus: "ทำให้ {topic} เป็นหัวข้อหลักของบทเรียนถัดไป",
    coachx_detail_action_keep_momentum: "ยอดเยี่ยม! รักษาหลักสูตรปัจจุบันและก้าวสู่ขั้นต่อไป",
    coachx_days_ago_label: "บทเรียนล่าสุด",
    // Members overview summary
    coachx_members_overview_title: "ภาพรวมการเติบโตของสมาชิก",
    coachx_members_avg_score: "คะแนนเติบโตเฉลี่ย",
    coachx_members_top_score: "คะแนนสูงสุด: {name} ({score} คะแนน)",
    coachx_member_search_placeholder: "ค้นหาชื่อสมาชิก...",
    coachx_member_search_empty: "ไม่พบสมาชิกที่ตรงกัน",
    // LessonCard
    media_load_error: "ไม่สามารถโหลดสื่อได้",
    record_type_round: "รอบ",
    record_type_lesson_rec: "บันทึกบทเรียน",
    record_type_practice: "ฝึกซ้อม",
    feedback_requested: "ขอฟีดแบค",
    feedback_completed: "ฟีดแบคเสร็จสิ้น",
    media_hidden: "ซ่อนสื่อ",
    view_detail: "ดูรายละเอียด",
    // ReservationManager
    reservation_tab_slots: "จัดการสล็อต",
    reservation_tab_calendar: "ปฏิทิน",
    reservation_tab_settings: "ตั้งค่าเวลาทำงาน",
    res_status_available: "ว่าง",
    res_status_blocked: "บล็อกแล้ว",
    res_status_pending: "รอดำเนินการ",
    res_status_confirmed: "ยืนยันแล้ว",
    res_status_cancelled: "ยกเลิกแล้ว",
    res_status_completed: "เสร็จสิ้น",
    slot_time_management: "จัดการช่วงเวลา",
    working_schedule_settings: "ตั้งค่าตารางทำงาน",
    working_hours_outside_hint: "สล็อตนอกเวลาทำงานจะไม่แสดงให้สมาชิก",
    approve_label: "อนุมัติ",
    reject_label: "ปฏิเสธ",
    release_label: "ยกเลิกบล็อก",
    confirm_approve_reservation: "อนุมัติการจองนี้?",
    reservation_approved_msg: "อนุมัติการจองแล้ว",
    reservation_rejected_msg: "ปฏิเสธการจองแล้ว",
    reject_reason_prompt: "กรอกเหตุผลการปฏิเสธ (ไม่บังคับ):",
    confirm_cancel_reservation: "ยกเลิกการจองนี้?",
    reservation_cancelled_msg: "ยกเลิกการจองแล้ว",
    working_hours_saved_msg: "บันทึกเวลาทำงานแล้ว",
    saving_label: "กำลังบันทึก...",
    save_working_hours: "บันทึกเวลาทำงาน",
    closed_day_label: "หยุด",
    holiday_day_msg: "วันนี้เป็นวันหยุด สามารถเปลี่ยนในการตั้งค่าเวลาทำงาน",
    reservation_count_all: "ทั้งหมด",
    no_reservations_label: "ไม่มีการจอง",
    slot_change_failed_msg: "อัปเดตสล็อตไม่สำเร็จ",
    approve_failed_msg: "การอนุมัติล้มเหลว",
    reject_failed_msg: "การปฏิเสธล้มเหลว",
    cancel_failed_msg: "การยกเลิกล้มเหลว",
    save_failed_msg: "บันทึกล้มเหลว",
    register_label: "ลงทะเบียน",
    unavailable_label: "ไม่ว่าง",
    day_sun: "อา",
    day_mon: "จ",
    day_tue: "อ",
    day_wed: "พ",
    day_thu: "พฤ",
    day_fri: "ศ",
    day_sat: "ส",
    // ClientProfileSettings
    my_profile_title: "การตั้งค่าโปรไฟล์",
    golf_profile_section: "โปรไฟล์กอล์ฟ",
    golf_experience_label: "ประสบการณ์กอล์ฟ",
    handicap_label: "แฮนดิแคป",
    best_score_label: "คะแนนดีที่สุด",
    bio_label: "แนะนำตัว / เป้าหมาย",
    club_bag_section: "ชุดไม้กอล์ฟ",
    no_clubs_registered: "ยังไม่มีไม้กอล์ฟที่ลงทะเบียน",
    club_brand_placeholder: "แบรนด์ (เช่น Titleist)",
    club_model_placeholder: "รุ่น (เช่น TSi3)",
    confirm_remove_coach: "ยกเลิกโค้ชที่กำหนด?",
    confirm_delete_club: "ลบไม้กอล์ฟนี้?",
    exp_years_unit: "ปี",
    exp_months_unit: "เดือน",
    stats_based_analysis: "การวิเคราะห์จากบันทึก ({n} เกม)",
    club_category_driver: "ไดรเวอร์",
    club_category_wood: "วูด/ยูทิลิตี้",
    club_category_iron: "ไอรอน",
    club_category_wedge: "เวดจ์",
    club_category_putter: "พัตเตอร์",
    driver_spec1: "ลอฟต์ (องศา)",
    driver_spec2: "แกน/ความแข็ง",
    wood_spec1: "หมายเลข/ลอฟต์",
    wood_spec2: "แกน/ความแข็ง",
    iron_spec1: "ชุด (เช่น 5-P)",
    iron_spec2: "แกน",
    wedge_spec1: "ลอฟต์ (องศา)",
    wedge_spec2: "บาวน์ซ/แกน",
    putter_spec1: "ความยาว (นิ้ว)",
    putter_spec2: "ประเภท (ใบมีด/มัลเล็ต)",
    spec1_generic: "สเปค 1",
    spec2_generic: "สเปค 2",
    // HomeworkModal
    homework_modal_title: "การบ้าน ({name})",
    homework_tab_list: "สถานะการบ้าน",
    homework_tab_assign: "การบ้านใหม่",
    homework_stats_title: "รายงานความคืบหน้า",
    homework_stats_count: "เสร็จ {completed} จาก {total} ข้อ",
    homework_task_list_title: "รายการการบ้าน",
    homework_empty: "ยังไม่มีการบ้าน",
    homework_done_confirmed: "ยืนยันเสร็จแล้ว",
    homework_task_label: "เนื้อหาการบ้าน",
    homework_start_date: "วันเริ่มต้น",
    homework_duration: "ระยะเวลา",
    homework_days_select: "เลือกวัน",
    homework_times_per_week: "{n} ครั้ง/สัปดาห์",
    homework_total_label: "จำนวนการบ้านทั้งหมด",
    homework_total_count_unit: "{n} ข้อ",
    homework_assign_btn: "กำหนดการบ้าน",
    homework_template_placeholder: "เทมเพลต...",
    homework_placeholder: "เช่น สวิงเปล่า 20 ครั้ง",
    hw_motivation_high: "ยอดเยี่ยม! 🏆",
    hw_motivation_mid: "ทำอย่างสม่ำเสมอ 👍",
    hw_motivation_low: "ต้องพยายามมากขึ้น 💪",
    hw_validation_no_content: "กรุณากรอกเนื้อหาการบ้าน",
    hw_validation_select_day: "เลือกอย่างน้อยหนึ่งวัน",
    hw_no_dates_generated: "ไม่มีวันที่ตรงกับช่วงเวลาและวันที่เลือก",
    hw_assign_success: "กำหนดการบ้าน {count} ข้อให้ {name} แล้ว",
    hw_assign_error: "เกิดข้อผิดพลาดในการกำหนดการบ้าน",
    hw_confirm_delete: "ลบการบ้านนี้?",
    close_label: "ปิด",
    duration_1w: "1 สัปดาห์ (7 วัน)",
    duration_2w: "2 สัปดาห์ (14 วัน)",
    duration_4w: "4 สัปดาห์ (1 เดือน)",
    duration_8w: "8 สัปดาห์ (2 เดือน)",
    duration_12w: "12 สัปดาห์ (3 เดือน)",
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ko');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
